### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by akshayv177** [rajeshroy402/install-deepstream-jetson#1]
This was the error message:
-- Configuring incomplete, errors occurred!
See also "/home/nvidia/install-deepstream-jetson/jetson-AI/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by rajeshroy402** [comment]
Can you please share the CMakeOutput.log file as well?

**Comment by rajeshroy402** [comment]
I have tested the jetson_inference file and it has no error. 
I am closing this issue.

Thanks
